schemaVersion: 1.0.0

code: hello-world
name: Hello World
description: A demo app to say hello to the world
developer: gh-dopsun
visibility: Public
copyright: © 2024 Appbnr Technologies Limited

release:
  version: 0.0.1
  summary: Draft release
